version: "2"
services:
  painting_web:
    container_name: painting_web
    build: .
    ports:
     - 80:9000
    volumes:
     - .:/code
     - ~/.ivy2:/root/.ivy2
    stdin_open: true
    command: bash -c "sbt clean stage && /code/target/universal/stage/bin/painting -Dconfig.file=/code/conf/application-prod.conf"
  painting_db:
      container_name: painting_db
      image: mongo:3.0
      command: mongod --smallfiles --quiet --logpath=/dev/null
      volumes:
       - painting_data:/var/lib/mongodb
      ports:
       - 27017:27017
volumes:
  painting_data:
