version: "2"
services:
  painting_web: 
    container_name: painting_web
    build: .
    ports:
     - 9000:9000
    volumes:
     - .:/code
    stdin_open: true
    command: bash -c "sbt run"
  painting_db:
      container_name: painting_db
      image: mongo:3.0
      command: mongod --smallfiles --quiet --logpath=/dev/null
      volumes:
        - painting_data:/var/lib/mongodb
      ports:
        - 27017:27017

volumes:
  painting_data: