version: "2"
services:
  painting_web:
    container_name: painting_web
    build: .
    ports:
     - 80:9000
    stdin_open: true
    command: bash -c "/code/target/universal/painting -Dconfig.file=/code/conf/application-prod.conf"
    environment:
      - PAINTING_MONGO_CONNECTION=mongodb://painting_db:27017/painting
  painting_db:
      container_name: painting_db
      image: mongo:3.0
      command: mongod --smallfiles --quiet --logpath=/dev/null
      volumes:
       - painting_data:/var/lib/mongodb
      ports:
       - 27017:27017
volumes:
  painting_data:
