version: "2"
services:
  painting-web:
    image: neil121183/painting:latest
    expose:
     - "9000"
    command: bash -c "/code/target/universal/painting -Dconfig.file=/code/conf/application-prod.conf"
    environment:
      - PAINTING_MONGO_CONNECTION=mongodb://painting-db:27017/painting
  painting-db:
      image: mongo:3.0
      command: mongod --smallfiles --quiet --logpath=/dev/null
      volumes:
       - painting_data:/var/lib/mongodb
      ports:
       - 27017:27017
  painting-lb:
    image: dockercloud/haproxy
    links:
      - painting-web
    environment:
      - 'HTTP_BASIC_AUTH=santa:secret'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
volumes:
  painting_data:
